version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RAVINDU12345
      MYSQL_DATABASE: todo_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
   
  backend:
    build: ./backend
    container_name: todo_backend
    restart: always
    environment:
      DB_USER: root
      DB_PASS: RAVINDU12345
      DB_NAME: todo_db
      DB_HOST: db          
    depends_on:
      - db
    ports:
      - "5000:5000"        # http://localhost:5000

  frontend:
    build: ./frontend
    container_name: todo_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"          # http://localhost:3000

volumes:
  mysql_data:

