version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: RAVINDU12345
      MYSQL_DATABASE: todo_db
      # MYSQL_USER: todo_user
      # MYSQL_PASSWORD: todo_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Use 3307 on host to avoid conflict with your existing local MySQL on 3306
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: todo_backend
    environment:
      DB_USER: root
      DB_PASS: RAVINDU12345
      DB_NAME: todo_db
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  # frontend:
  #   build: ./frontend
  #   container_name: todo_frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     VITE_BACKEND_URL: http://backend:5000

volumes:
  mysql_data:
